# Generated by Django 4.2.30 on 2026-04-20 07:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_alter_actor_actor_id_alter_actor_actor_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Segment',
            fields=[
                ('segment_id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('script_content', models.TextField(blank=True, null=True)),
                ('summary_content', models.TextField(blank=True, null=True)),
                ('segment_order', models.IntegerField(blank=True, null=True)),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='segments', to='movies.movie')),
            ],
        ),
    ]
